vich_uploader:
    db_driver: orm

    mappings:
        code:
            uri_prefix: /files/codes
            upload_destination: '%kernel.project_dir%/public/files/codes'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
